const int colortex0Format = R11F_G11F_B10F
const int colortex1Format = RGB8
const int colortex2Format = RGB8
const int colortex3Format = R8

const int   shadowMapResolution = 1024
const float shadowDistance      = 128.0
const float shadowMapBias       = 1.0 - 25.6 / shadowDistance

const bool  shadowHardwareFiltering = true

const float fogStart = 0.6

uniform.float.u_snapResolution  = 120.0
uniform.float.u_affineStrength  = 0.25
uniform.float.u_ditherStrength  = 0.4
uniform.bool.u_snapEnabled    = 0
uniform.bool.u_affineEnabled  = 0
uniform.bool.u_ditherEnabled  = 0
uniform.bool.u_fogEnabled     = 0
uniform.bool.u_pixelateEnabled = 0

profile.MINIMUM  = !u_snapEnabled u_snapResolution=80 !u_affineEnabled !u_ditherEnabled !u_fogEnabled !u_pixelateEnabled
profile.LOW      = u_snapEnabled u_snapResolution=120 !u_affineEnabled !u_ditherEnabled !u_fogEnabled !u_pixelateEnabled
profile.MEDIUM   = u_snapEnabled u_snapResolution=120 u_affineEnabled u_ditherEnabled u_fogEnabled !u_pixelateEnabled
profile.HIGH     = u_snapEnabled u_snapResolution=160 u_affineEnabled u_ditherEnabled u_fogEnabled !u_pixelateEnabled
profile.ULTRA    = u_snapEnabled u_snapResolution=160 u_affineEnabled u_ditherEnabled u_fogEnabled u_pixelateEnabled

screen = <empty> <empty> [PSX_EFFECTS] <profile>

screen.PSX_EFFECTS = <empty> <empty> u_snapEnabled u_snapResolution u_affineEnabled u_affineStrength \
                     <empty> <empty> u_ditherEnabled u_ditherStrength u_fogEnabled \
                     <empty> <empty> u_pixelateEnabled

sliders = u_snapResolution u_affineStrength u_ditherStrength

oldHandLight    = false
oldLighting     = false
underwaterOverlay = false
